import type { StudyQuestion } from "@/lib/types";

export const extraQuestions: StudyQuestion[] = [
  {
    id: "SQL-11",
    type: "sql",
    topic: "LEFT JOIN",
    question:
      "DEPT(dept_id, dept_name) 와 EMP(emp_id, dept_id) 테이블이 있다. 직원이 한 명도 없는 부서도 포함해서 부서명과 직원 수를 조회하는 SQL을 작성하시오.",
    answer:
      "SELECT d.dept_name, COUNT(e.emp_id) AS emp_count\nFROM DEPT d\nLEFT JOIN EMP e ON d.dept_id = e.dept_id\nGROUP BY d.dept_name;",
    explanation:
      "직원이 없는 부서도 포함해야 하므로 LEFT JOIN을 써야 한다. COUNT(e.emp_id)는 NULL을 세지 않으므로 빈 부서는 0으로 집계된다.",
    difficulty: "기본",
    sourceNote: "2022~2025 조인/집계 복합 패턴 반영",
  },
  {
    id: "SQL-12",
    type: "sql",
    topic: "DELETE",
    question:
      "LOG(log_id, created_at) 테이블에서 created_at이 '2025-01-01'보다 이전인 데이터를 삭제하는 SQL을 작성하시오.",
    answer: "DELETE FROM LOG\nWHERE created_at < '2025-01-01';",
    explanation:
      "삭제 범위를 제한하는 WHERE 절이 핵심이다. DELETE는 단순 문법보다 조건 누락 위험을 같이 떠올리는 연습이 중요하다.",
    difficulty: "입문",
    sourceNote: "실무형 DML 정리 문제 반영",
  },
  {
    id: "SQL-13",
    type: "sql",
    topic: "CASE 집계",
    question:
      "ORDERS(order_id, status) 테이블에서 status가 'DONE'인 건수를 done_count라는 이름으로 조회하는 SQL을 작성하시오.",
    answer:
      "SELECT SUM(CASE WHEN status = 'DONE' THEN 1 ELSE 0 END) AS done_count\nFROM ORDERS;",
    explanation:
      "조건부 집계는 CASE와 SUM 조합으로 자주 만든다. 실전형 SQL에서 상태별 집계로 자주 바뀌어 나온다.",
    difficulty: "실전",
    sourceNote: "2023~2025 조건부 집계 유형 반영",
  },
  {
    id: "SQL-14",
    type: "sql",
    topic: "LIKE 검색",
    question:
      "USER_INFO(user_id, user_name) 테이블에서 이름에 '김'이 포함된 사용자만 조회하는 SQL을 작성하시오.",
    answer: "SELECT user_id, user_name\nFROM USER_INFO\nWHERE user_name LIKE '%김%';",
    explanation:
      "문자 패턴 검색은 LIKE와 와일드카드(%)를 함께 쓴다. 단순하지만 실수하기 쉬운 기본 패턴이다.",
    difficulty: "입문",
    sourceNote: "문자열 조건 검색 기초 반영",
  },
  {
    id: "SQL-15",
    type: "sql",
    topic: "COMMIT",
    question:
      "INSERT와 UPDATE 작업을 정상적으로 끝낸 뒤 변경 사항을 영구 반영하려고 한다. 실행할 SQL 문을 작성하시오.",
    answer: "COMMIT;",
    explanation:
      "트랜잭션 완료 후 변경 내용을 확정하는 명령은 COMMIT이다. SAVEPOINT, ROLLBACK과 함께 세트로 정리하는 것이 좋다.",
    difficulty: "입문",
    sourceNote: "트랜잭션 제어문 핵심 정리 반영",
  },
  {
    id: "JAVA-11",
    type: "java",
    topic: "final",
    question: "final 키워드를 변수에 붙였을 때의 의미를 한 줄로 설명하시오.",
    answer: "초기화된 이후 값을 다시 대입할 수 없다는 의미다.",
    explanation: "final은 재할당 금지를 나타낸다. 상수와 불변 개념의 기초라서 자주 묻는다.",
    difficulty: "입문",
    sourceNote: "Java 기본 문법 단답형 강화",
  },
  {
    id: "JAVA-12",
    type: "java",
    topic: "ArrayList",
    question:
      "다음 코드의 실행 결과를 쓰시오.\n\nimport java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    List<Integer> list = new ArrayList<>();\n    list.add(10);\n    list.add(20);\n    list.remove(0);\n    System.out.print(list.size());\n  }\n}",
    answer: "1",
    explanation: "0번 인덱스 요소를 제거하면 하나만 남는다. List의 add, remove, size는 가장 기본적인 조작이다.",
    difficulty: "입문",
    sourceNote: "컬렉션 기초 문제 보강",
  },
  {
    id: "JAVA-13",
    type: "java",
    topic: "기본형 형변환",
    question:
      "int a = 10; double b = a; 일 때, 이 대입이 가능한 이유를 한 줄로 설명하시오.",
    answer: "작은 범위의 int가 더 큰 범위의 double로 자동 형변환(묵시적 형변환)되기 때문이다.",
    explanation: "기본형 변환 규칙은 짧은 단답형으로 자주 확인된다. 확대 변환은 자동, 축소 변환은 명시적 캐스팅이 필요하다.",
    difficulty: "기본",
    sourceNote: "Java 형변환 기초 개념 반영",
  },
  {
    id: "JAVA-14",
    type: "java",
    topic: "예외 종류",
    question: "배열 범위를 벗어난 인덱스 접근 시 자주 발생하는 예외 클래스명을 쓰시오.",
    answer: "ArrayIndexOutOfBoundsException",
    explanation: "런타임 예외 이름을 정확히 쓰는 문제는 기초 문법과 디버깅 감각을 함께 확인할 때 자주 나온다.",
    difficulty: "기본",
    sourceNote: "예외 처리 파트 보강",
  },
  {
    id: "JAVA-15",
    type: "java",
    topic: "default 메서드",
    question: "Java 인터페이스의 default 메서드는 왜 도입되었는지 한 줄로 설명하시오.",
    answer: "기존 구현 클래스를 깨지 않으면서 인터페이스에 기본 동작을 추가하기 위해 도입되었다.",
    explanation: "interface 관련 서술형이 나올 때 계약과 확장성 관점에서 설명할 수 있어야 한다.",
    difficulty: "실전",
    sourceNote: "Java 인터페이스 심화 개념 반영",
  },
  {
    id: "DESC-11",
    type: "descriptive",
    topic: "캡슐화",
    question: "객체지향의 캡슐화를 간단히 설명하시오.",
    answer: "데이터와 그 데이터를 다루는 메서드를 하나로 묶고, 외부에서 직접 접근하지 못하도록 필요한 부분만 공개하는 것이다.",
    explanation: "추상화, 상속, 다형성과 함께 4대 특성으로 자주 비교된다. 정보 은닉과 연결해 기억하면 좋다.",
    difficulty: "기본",
    sourceNote: "객체지향 기본 이론 보강",
  },
  {
    id: "DESC-12",
    type: "descriptive",
    topic: "동등 분할",
    question: "동등 분할 테스트 기법을 간단히 설명하시오.",
    answer: "입력값을 비슷한 성격의 여러 구간으로 나누고, 각 구간에서 대표값을 선택해 테스트하는 기법이다.",
    explanation: "경계값 분석과 세트로 묶여 자주 나온다. 둘의 차이는 경계 집중 여부다.",
    difficulty: "기본",
    sourceNote: "테스트 설계 기법 보강",
  },
  {
    id: "DESC-13",
    type: "descriptive",
    topic: "대칭키와 비대칭키",
    question: "대칭키 암호화와 비대칭키 암호화의 차이를 간단히 설명하시오.",
    answer: "대칭키는 암호화와 복호화에 같은 키를 사용하고, 비대칭키는 공개키와 개인키처럼 서로 다른 키를 사용한다.",
    explanation: "보안 파트 단답형에서 매우 자주 나오는 비교 문제다. 속도와 키 배포 측면도 함께 떠올리면 좋다.",
    difficulty: "기본",
    sourceNote: "보안 기초 이론 보강",
  },
  {
    id: "DESC-14",
    type: "descriptive",
    topic: "회귀 테스트",
    question: "회귀 테스트의 목적을 설명하시오.",
    answer: "기능 수정이나 변경 후 기존에 정상 동작하던 부분이 깨지지 않았는지 확인하는 것이다.",
    explanation: "실무형 테스트 개념으로 자주 나오는 주제다. 변경 이후 기존 기능 검증이라는 문장을 기억하면 된다.",
    difficulty: "기본",
    sourceNote: "테스트 운영 관점 보강",
  },
  {
    id: "DESC-15",
    type: "descriptive",
    topic: "REST",
    question: "REST 방식의 핵심 특징 두 가지를 간단히 쓰시오.",
    answer: "예시: 자원을 URI로 표현한다, 요청은 무상태(stateless)로 처리한다.",
    explanation: "HTTP/웹 개념과 함께 요약형으로 자주 정리되는 주제다. URI, 무상태, 자원 중심을 묶어두면 좋다.",
    difficulty: "실전",
    sourceNote: "웹 서비스 기본 개념 보강",
  },
  {
    id: "CONCEPT-11",
    type: "concept",
    topic: "회귀 테스트",
    question: "수정한 코드가 기존 기능에 영향을 주지 않았는지 확인하는 테스트를 무엇이라고 하는가?",
    answer: "회귀 테스트",
    explanation: "변경 이후 기존 동작이 유지되는지 보는 테스트다. 배포 전 핵심 확인 절차로 자주 나온다.",
    difficulty: "입문",
    sourceNote: "테스트 운영 빈출 개념 반영",
  },
  {
    id: "CONCEPT-12",
    type: "concept",
    topic: "세마포어",
    question: "공유 자원 접근을 제어하기 위해 사용하는 동기화 도구를 무엇이라고 하는가?",
    answer: "세마포어(Semaphore)",
    explanation: "운영체제의 동기화 기본 개념이다. wait와 signal 연산과 함께 정리하는 편이 좋다.",
    difficulty: "기본",
    sourceNote: "운영체제 동기화 개념 보강",
  },
  {
    id: "CONCEPT-13",
    type: "concept",
    topic: "해시",
    question: "임의 길이 데이터를 고정 길이 값으로 변환하는 함수를 무엇이라고 하는가?",
    answer: "해시 함수(Hash Function)",
    explanation: "보안과 자료구조 모두에서 기본이 되는 용어다. 일방향성과 무결성 확인 키워드와 연결해두면 좋다.",
    difficulty: "입문",
    sourceNote: "보안/자료구조 공통 기초 개념 반영",
  },
  {
    id: "CONCEPT-14",
    type: "concept",
    topic: "HTTP 무상태성",
    question: "HTTP가 요청 사이의 서버 상태를 기본적으로 유지하지 않는 성질을 무엇이라고 하는가?",
    answer: "무상태성(Stateless)",
    explanation: "REST와 HTTP를 함께 공부할 때 가장 먼저 정리해야 하는 성질이다.",
    difficulty: "기본",
    sourceNote: "웹 서비스 기초 개념 보강",
  },
  {
    id: "CONCEPT-15",
    type: "concept",
    topic: "요구사항 추적성",
    question: "요구사항에서 설계, 구현, 테스트 결과까지 연결해 확인할 수 있는 특성을 무엇이라고 하는가?",
    answer: "추적 가능성(Traceability)",
    explanation: "요구사항 품질 속성 중 하나로 시험에서 짧게 물어보기 좋은 개념이다.",
    difficulty: "기본",
    sourceNote: "요구사항 분석 보강",
  },
  {
    id: "SQL-16",
    type: "sql",
    topic: "UNION",
    question: "TABLE_A(id)와 TABLE_B(id)에서 중복을 제거한 전체 id 목록을 조회하는 SQL을 작성하시오.",
    answer: "SELECT id FROM TABLE_A\nUNION\nSELECT id FROM TABLE_B;",
    explanation: "UNION은 결과를 합치면서 중복을 제거한다. UNION ALL과 차이를 같이 정리해 두면 좋다.",
    difficulty: "기본",
    sourceNote: "집합 연산자 반복 개념 보강",
  },
  {
    id: "SQL-17",
    type: "sql",
    topic: "서브쿼리",
    question: "EMP(emp_id, salary) 테이블에서 전체 평균 급여보다 높은 직원만 조회하는 SQL을 작성하시오.",
    answer: "SELECT emp_id, salary\nFROM EMP\nWHERE salary > (SELECT AVG(salary) FROM EMP);",
    explanation: "비교 대상이 집계 결과 하나라면 단일행 서브쿼리를 WHERE에 둘 수 있다.",
    difficulty: "기본",
    sourceNote: "2022~2025 서브쿼리 기본 패턴 반영",
  },
  {
    id: "SQL-18",
    type: "sql",
    topic: "ORDER BY 다중 정렬",
    question: "SCORE(student_id, grade, score) 테이블에서 grade 오름차순, score 내림차순으로 조회하는 SQL을 작성하시오.",
    answer: "SELECT student_id, grade, score\nFROM SCORE\nORDER BY grade ASC, score DESC;",
    explanation: "ORDER BY는 여러 컬럼을 순서대로 줄 수 있다. 첫 번째 정렬 기준이 같을 때 다음 기준이 적용된다.",
    difficulty: "입문",
    sourceNote: "정렬 기본 패턴 보강",
  },
  {
    id: "SQL-19",
    type: "sql",
    topic: "BETWEEN",
    question: "PRODUCT(prod_id, price) 테이블에서 price가 10000 이상 30000 이하인 상품만 조회하는 SQL을 작성하시오.",
    answer: "SELECT prod_id, price\nFROM PRODUCT\nWHERE price BETWEEN 10000 AND 30000;",
    explanation: "BETWEEN A AND B는 양 끝값을 포함한다. 비교식을 줄여 쓰는 기본 문법이다.",
    difficulty: "입문",
    sourceNote: "조건 검색 기초 보강",
  },
  {
    id: "SQL-20",
    type: "sql",
    topic: "ROLLBACK",
    question: "트랜잭션 작업 전체를 취소하려고 할 때 사용하는 SQL 문을 작성하시오.",
    answer: "ROLLBACK;",
    explanation: "COMMIT이 확정이라면 ROLLBACK은 전체 취소다. SAVEPOINT와 함께 묶여 자주 나온다.",
    difficulty: "입문",
    sourceNote: "트랜잭션 제어문 보강",
  },
  {
    id: "JAVA-16",
    type: "java",
    topic: "오버로딩",
    question: "오버로딩과 오버라이딩의 차이를 한 줄로 설명하시오.",
    answer: "오버로딩은 같은 이름의 메서드를 매개변수만 다르게 여러 개 정의하는 것이고, 오버라이딩은 상속 관계에서 부모 메서드를 재정의하는 것이다.",
    explanation: "둘을 섞어 묻는 문제가 매우 많다. 선언 위치와 매개변수 기준을 같이 떠올리면 구분이 쉽다.",
    difficulty: "기본",
    sourceNote: "Java 객체지향 핵심 비교 보강",
  },
  {
    id: "JAVA-17",
    type: "java",
    topic: "this",
    question: "Java에서 this 키워드가 가리키는 대상을 한 줄로 설명하시오.",
    answer: "현재 메서드나 생성자를 실행 중인 객체 자신을 가리킨다.",
    explanation: "필드와 매개변수 이름이 같을 때 구분하는 용도로 자주 나온다.",
    difficulty: "입문",
    sourceNote: "Java 기초 문법 보강",
  },
  {
    id: "JAVA-18",
    type: "java",
    topic: "StringBuilder",
    question: "문자열을 반복해서 이어 붙일 때 String보다 StringBuilder가 자주 추천되는 이유를 한 줄로 설명하시오.",
    answer: "문자열 변경 작업이 많을 때 불필요한 새 객체 생성을 줄여 성능상 유리하기 때문이다.",
    explanation: "불변 객체인 String과 변경 가능한 StringBuilder의 차이를 이해하면 된다.",
    difficulty: "기본",
    sourceNote: "문자열 처리 실무형 개념 보강",
  },
  {
    id: "JAVA-19",
    type: "java",
    topic: "접근 제어자",
    question: "같은 클래스 내부에서만 접근 가능하도록 제한하는 접근 제어자는 무엇인가?",
    answer: "private",
    explanation: "public, protected, default, private의 기본 접근 범위는 자주 나오는 단답형이다.",
    difficulty: "입문",
    sourceNote: "접근 제어 기초 보강",
  },
  {
    id: "JAVA-20",
    type: "java",
    topic: "super",
    question: "Java에서 super 키워드의 대표적인 용도 두 가지를 간단히 쓰시오.",
    answer: "부모 클래스의 필드나 메서드에 접근할 때 사용하고, 부모 생성자를 호출할 때 사용한다.",
    explanation: "this와 super는 짝으로 자주 출제된다. 부모 참조와 생성자 호출을 묶어 기억하면 좋다.",
    difficulty: "기본",
    sourceNote: "상속 키워드 보강",
  },
  {
    id: "DESC-16",
    type: "descriptive",
    topic: "다형성",
    question: "객체지향의 다형성을 간단히 설명하시오.",
    answer: "같은 메시지나 메서드 호출에 대해 객체의 실제 타입에 따라 다른 동작을 수행할 수 있는 특성이다.",
    explanation: "상속과 오버라이딩을 같이 설명할 때 자주 연결되는 핵심 개념이다.",
    difficulty: "기본",
    sourceNote: "객체지향 이론 보강",
  },
  {
    id: "DESC-17",
    type: "descriptive",
    topic: "비정규화",
    question: "비정규화를 수행하는 대표 목적을 간단히 설명하시오.",
    answer: "조회 성능 향상이나 개발 편의성을 위해 중복을 일부 허용하며 테이블 구조를 단순화하는 것이다.",
    explanation: "정규화와 반대 방향 개념으로 출제될 수 있다. 무결성과 성능의 trade-off를 떠올리면 된다.",
    difficulty: "실전",
    sourceNote: "데이터 모델링 심화 보강",
  },
  {
    id: "DESC-18",
    type: "descriptive",
    topic: "교착상태",
    question: "운영체제의 교착상태(deadlock)를 한 줄로 설명하시오.",
    answer: "둘 이상의 프로세스가 서로가 가진 자원을 기다리며 무한히 진행하지 못하는 상태다.",
    explanation: "운영체제에서 자주 나오는 정의형 문제다. 상호배제, 점유와 대기 같은 조건과 연결된다.",
    difficulty: "기본",
    sourceNote: "운영체제 이론 보강",
  },
  {
    id: "DESC-19",
    type: "descriptive",
    topic: "IPv4와 IPv6",
    question: "IPv4와 IPv6의 가장 큰 차이를 한 줄로 설명하시오.",
    answer: "IPv4는 32비트 주소 체계이고, IPv6는 128비트 주소 체계로 훨씬 더 많은 주소 공간을 제공한다.",
    explanation: "주소 길이와 표기 방식 차이를 같이 떠올리면 네트워크 문제 대응이 쉬워진다.",
    difficulty: "기본",
    sourceNote: "네트워크 기초 보강",
  },
  {
    id: "DESC-20",
    type: "descriptive",
    topic: "요구사항 검증 가능성",
    question: "요구사항의 검증 가능성이 무엇을 의미하는지 설명하시오.",
    answer: "요구사항이 테스트나 리뷰 등을 통해 충족 여부를 확인할 수 있는 형태로 작성되어 있어야 한다는 의미다.",
    explanation: "좋은 요구사항 특성 중 하나로, 모호한 문장 대신 측정 가능한 표현이 중요하다.",
    difficulty: "기본",
    sourceNote: "요구사항 품질 보강",
  },
  {
    id: "CONCEPT-16",
    type: "concept",
    topic: "교착상태",
    question: "프로세스들이 서로 자원을 기다리며 멈춰버리는 상태를 무엇이라고 하는가?",
    answer: "교착상태(Deadlock)",
    explanation: "운영체제 기초에서 자주 나오는 용어다.",
    difficulty: "입문",
    sourceNote: "운영체제 핵심 용어 보강",
  },
  {
    id: "CONCEPT-17",
    type: "concept",
    topic: "UNION ALL",
    question: "두 SELECT 결과를 중복 제거 없이 합치는 연산자는 무엇인가?",
    answer: "UNION ALL",
    explanation: "UNION은 중복 제거, UNION ALL은 중복 유지라는 차이를 정확히 기억해야 한다.",
    difficulty: "입문",
    sourceNote: "집합 연산자 보강",
  },
  {
    id: "CONCEPT-18",
    type: "concept",
    topic: "private",
    question: "접근 제어자 중 같은 클래스 내부에서만 접근 가능한 것은 무엇인가?",
    answer: "private",
    explanation: "접근 범위 문제에서 가장 기본이 되는 키워드다.",
    difficulty: "입문",
    sourceNote: "Java 접근 제어 용어 보강",
  },
  {
    id: "CONCEPT-19",
    type: "concept",
    topic: "기본키",
    question: "테이블에서 각 행을 유일하게 식별하는 키를 무엇이라고 하는가?",
    answer: "기본키(Primary Key)",
    explanation: "중복과 NULL을 허용하지 않는다는 점까지 같이 기억해 두면 좋다.",
    difficulty: "입문",
    sourceNote: "데이터베이스 기본 용어 보강",
  },
  {
    id: "CONCEPT-20",
    type: "concept",
    topic: "오버로딩",
    question: "같은 이름의 메서드를 매개변수 목록만 다르게 여러 개 정의하는 것을 무엇이라고 하는가?",
    answer: "오버로딩(Overloading)",
    explanation: "오버라이딩과 구분하는 대표 단답형 문제다.",
    difficulty: "입문",
    sourceNote: "Java 메서드 개념 보강",
  }
];

