import type { StudyQuestion } from "@/lib/types";

export const extraQuestions: StudyQuestion[] = [
  {
    id: "SQL-11",
    type: "sql",
    topic: "LEFT JOIN",
    question:
      "DEPT(dept_id, dept_name) 와 EMP(emp_id, dept_id) 테이블이 있다. 직원이 한 명도 없는 부서도 포함해서 부서명과 직원 수를 조회하는 SQL을 작성하시오.",
    answer:
      "SELECT d.dept_name, COUNT(e.emp_id) AS emp_count\nFROM DEPT d\nLEFT JOIN EMP e ON d.dept_id = e.dept_id\nGROUP BY d.dept_name;",
    explanation:
      "직원이 없는 부서도 포함해야 하므로 LEFT JOIN을 써야 한다. COUNT(e.emp_id)는 NULL을 세지 않으므로 빈 부서는 0으로 집계된다.",
    difficulty: "기본",
    sourceNote: "2022~2025 조인/집계 복합 패턴 반영",
  },
  {
    id: "SQL-12",
    type: "sql",
    topic: "DELETE",
    question:
      "LOG(log_id, created_at) 테이블에서 created_at이 '2025-01-01'보다 이전인 데이터를 삭제하는 SQL을 작성하시오.",
    answer: "DELETE FROM LOG\nWHERE created_at < '2025-01-01';",
    explanation:
      "삭제 범위를 제한하는 WHERE 절이 핵심이다. DELETE는 단순 문법보다 조건 누락 위험을 같이 떠올리는 연습이 중요하다.",
    difficulty: "입문",
    sourceNote: "실무형 DML 정리 문제 반영",
  },
  {
    id: "SQL-13",
    type: "sql",
    topic: "CASE 집계",
    question:
      "ORDERS(order_id, status) 테이블에서 status가 'DONE'인 건수를 done_count라는 이름으로 조회하는 SQL을 작성하시오.",
    answer:
      "SELECT SUM(CASE WHEN status = 'DONE' THEN 1 ELSE 0 END) AS done_count\nFROM ORDERS;",
    explanation:
      "조건부 집계는 CASE와 SUM 조합으로 자주 만든다. 실전형 SQL에서 상태별 집계로 자주 바뀌어 나온다.",
    difficulty: "실전",
    sourceNote: "2023~2025 조건부 집계 유형 반영",
  },
  {
    id: "SQL-14",
    type: "sql",
    topic: "LIKE 검색",
    question:
      "USER_INFO(user_id, user_name) 테이블에서 이름에 '김'이 포함된 사용자만 조회하는 SQL을 작성하시오.",
    answer: "SELECT user_id, user_name\nFROM USER_INFO\nWHERE user_name LIKE '%김%';",
    explanation:
      "문자 패턴 검색은 LIKE와 와일드카드(%)를 함께 쓴다. 단순하지만 실수하기 쉬운 기본 패턴이다.",
    difficulty: "입문",
    sourceNote: "문자열 조건 검색 기초 반영",
  },
  {
    id: "SQL-15",
    type: "sql",
    topic: "COMMIT",
    question:
      "INSERT와 UPDATE 작업을 정상적으로 끝낸 뒤 변경 사항을 영구 반영하려고 한다. 실행할 SQL 문을 작성하시오.",
    answer: "COMMIT;",
    explanation:
      "트랜잭션 완료 후 변경 내용을 확정하는 명령은 COMMIT이다. SAVEPOINT, ROLLBACK과 함께 세트로 정리하는 것이 좋다.",
    difficulty: "입문",
    sourceNote: "트랜잭션 제어문 핵심 정리 반영",
  },
  {
    id: "JAVA-11",
    type: "java",
    topic: "final",
    question: "final 키워드를 변수에 붙였을 때의 의미를 한 줄로 설명하시오.",
    answer: "초기화된 이후 값을 다시 대입할 수 없다는 의미다.",
    explanation: "final은 재할당 금지를 나타낸다. 상수와 불변 개념의 기초라서 자주 묻는다.",
    difficulty: "입문",
    sourceNote: "Java 기본 문법 단답형 강화",
  },
  {
    id: "JAVA-12",
    type: "java",
    topic: "ArrayList",
    question:
      "다음 코드의 실행 결과를 쓰시오.\n\nimport java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    List<Integer> list = new ArrayList<>();\n    list.add(10);\n    list.add(20);\n    list.remove(0);\n    System.out.print(list.size());\n  }\n}",
    answer: "1",
    explanation: "0번 인덱스 요소를 제거하면 하나만 남는다. List의 add, remove, size는 가장 기본적인 조작이다.",
    difficulty: "입문",
    sourceNote: "컬렉션 기초 문제 보강",
  },
  {
    id: "JAVA-13",
    type: "java",
    topic: "기본형 형변환",
    question:
      "int a = 10; double b = a; 일 때, 이 대입이 가능한 이유를 한 줄로 설명하시오.",
    answer: "작은 범위의 int가 더 큰 범위의 double로 자동 형변환(묵시적 형변환)되기 때문이다.",
    explanation: "기본형 변환 규칙은 짧은 단답형으로 자주 확인된다. 확대 변환은 자동, 축소 변환은 명시적 캐스팅이 필요하다.",
    difficulty: "기본",
    sourceNote: "Java 형변환 기초 개념 반영",
  },
  {
    id: "JAVA-14",
    type: "java",
    topic: "예외 종류",
    question: "배열 범위를 벗어난 인덱스 접근 시 자주 발생하는 예외 클래스명을 쓰시오.",
    answer: "ArrayIndexOutOfBoundsException",
    explanation: "런타임 예외 이름을 정확히 쓰는 문제는 기초 문법과 디버깅 감각을 함께 확인할 때 자주 나온다.",
    difficulty: "기본",
    sourceNote: "예외 처리 파트 보강",
  },
  {
    id: "JAVA-15",
    type: "java",
    topic: "default 메서드",
    question: "Java 인터페이스의 default 메서드는 왜 도입되었는지 한 줄로 설명하시오.",
    answer: "기존 구현 클래스를 깨지 않으면서 인터페이스에 기본 동작을 추가하기 위해 도입되었다.",
    explanation: "interface 관련 서술형이 나올 때 계약과 확장성 관점에서 설명할 수 있어야 한다.",
    difficulty: "실전",
    sourceNote: "Java 인터페이스 심화 개념 반영",
  },
  {
    id: "DESC-11",
    type: "descriptive",
    topic: "캡슐화",
    question: "객체지향의 캡슐화를 간단히 설명하시오.",
    answer: "데이터와 그 데이터를 다루는 메서드를 하나로 묶고, 외부에서 직접 접근하지 못하도록 필요한 부분만 공개하는 것이다.",
    explanation: "추상화, 상속, 다형성과 함께 4대 특성으로 자주 비교된다. 정보 은닉과 연결해 기억하면 좋다.",
    difficulty: "기본",
    sourceNote: "객체지향 기본 이론 보강",
  },
  {
    id: "DESC-12",
    type: "descriptive",
    topic: "동등 분할",
    question: "동등 분할 테스트 기법을 간단히 설명하시오.",
    answer: "입력값을 비슷한 성격의 여러 구간으로 나누고, 각 구간에서 대표값을 선택해 테스트하는 기법이다.",
    explanation: "경계값 분석과 세트로 묶여 자주 나온다. 둘의 차이는 경계 집중 여부다.",
    difficulty: "기본",
    sourceNote: "테스트 설계 기법 보강",
  },
  {
    id: "DESC-13",
    type: "descriptive",
    topic: "대칭키와 비대칭키",
    question: "대칭키 암호화와 비대칭키 암호화의 차이를 간단히 설명하시오.",
    answer: "대칭키는 암호화와 복호화에 같은 키를 사용하고, 비대칭키는 공개키와 개인키처럼 서로 다른 키를 사용한다.",
    explanation: "보안 파트 단답형에서 매우 자주 나오는 비교 문제다. 속도와 키 배포 측면도 함께 떠올리면 좋다.",
    difficulty: "기본",
    sourceNote: "보안 기초 이론 보강",
  },
  {
    id: "DESC-14",
    type: "descriptive",
    topic: "회귀 테스트",
    question: "회귀 테스트의 목적을 설명하시오.",
    answer: "기능 수정이나 변경 후 기존에 정상 동작하던 부분이 깨지지 않았는지 확인하는 것이다.",
    explanation: "실무형 테스트 개념으로 자주 나오는 주제다. 변경 이후 기존 기능 검증이라는 문장을 기억하면 된다.",
    difficulty: "기본",
    sourceNote: "테스트 운영 관점 보강",
  },
  {
    id: "DESC-15",
    type: "descriptive",
    topic: "REST",
    question: "REST 방식의 핵심 특징 두 가지를 간단히 쓰시오.",
    answer: "예시: 자원을 URI로 표현한다, 요청은 무상태(stateless)로 처리한다.",
    explanation: "HTTP/웹 개념과 함께 요약형으로 자주 정리되는 주제다. URI, 무상태, 자원 중심을 묶어두면 좋다.",
    difficulty: "실전",
    sourceNote: "웹 서비스 기본 개념 보강",
  },
  {
    id: "CONCEPT-11",
    type: "concept",
    topic: "회귀 테스트",
    question: "수정한 코드가 기존 기능에 영향을 주지 않았는지 확인하는 테스트를 무엇이라고 하는가?",
    answer: "회귀 테스트",
    explanation: "변경 이후 기존 동작이 유지되는지 보는 테스트다. 배포 전 핵심 확인 절차로 자주 나온다.",
    difficulty: "입문",
    sourceNote: "테스트 운영 빈출 개념 반영",
  },
  {
    id: "CONCEPT-12",
    type: "concept",
    topic: "세마포어",
    question: "공유 자원 접근을 제어하기 위해 사용하는 동기화 도구를 무엇이라고 하는가?",
    answer: "세마포어(Semaphore)",
    explanation: "운영체제의 동기화 기본 개념이다. wait와 signal 연산과 함께 정리하는 편이 좋다.",
    difficulty: "기본",
    sourceNote: "운영체제 동기화 개념 보강",
  },
  {
    id: "CONCEPT-13",
    type: "concept",
    topic: "해시",
    question: "임의 길이 데이터를 고정 길이 값으로 변환하는 함수를 무엇이라고 하는가?",
    answer: "해시 함수(Hash Function)",
    explanation: "보안과 자료구조 모두에서 기본이 되는 용어다. 일방향성과 무결성 확인 키워드와 연결해두면 좋다.",
    difficulty: "입문",
    sourceNote: "보안/자료구조 공통 기초 개념 반영",
  },
  {
    id: "CONCEPT-14",
    type: "concept",
    topic: "HTTP 무상태성",
    question: "HTTP가 요청 사이의 서버 상태를 기본적으로 유지하지 않는 성질을 무엇이라고 하는가?",
    answer: "무상태성(Stateless)",
    explanation: "REST와 HTTP를 함께 공부할 때 가장 먼저 정리해야 하는 성질이다.",
    difficulty: "기본",
    sourceNote: "웹 서비스 기초 개념 보강",
  },
  {
    id: "CONCEPT-15",
    type: "concept",
    topic: "요구사항 추적성",
    question: "요구사항에서 설계, 구현, 테스트 결과까지 연결해 확인할 수 있는 특성을 무엇이라고 하는가?",
    answer: "추적 가능성(Traceability)",
    explanation: "요구사항 품질 속성 중 하나로 시험에서 짧게 물어보기 좋은 개념이다.",
    difficulty: "기본",
    sourceNote: "요구사항 분석 보강",
  },
];
